name: farkha_app
description: "A new Flutter project."
publish_to: "none"
version: 5.4.9+26

environment:
  sdk: ^3.7.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1
  percent_indicator: ^4.2.5
  weather_icons: ^3.0.0
  flutter_markdown: ^0.7.7+1
  markdown: ^7.3.0
  tutorial_coach_mark: ^1.3.1

  # State Management & Navigation
  get: ^4.7.2
  get_storage: ^2.1.1

  # Firebase Services
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  firebase_messaging: ^16.0.2
  cloud_firestore: ^6.0.0

  # Ads
  google_mobile_ads: ^6.0.0
  gma_mediation_meta: ^1.4.3

  # Notifications
  flutter_local_notifications: ^19.5.0

  # Network & API
  http: ^1.3.0
  flutter_dotenv: ^6.0.0

  # Location Services
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  permission_handler: ^12.0.0+1

  # Localization
  intl: ^0.20.2
  flutter_localization: ^0.3.1

  # Utilities
  dartz: ^0.10.1
  vector_math: ^2.2.0
  share_plus: ^12.0.1
  url_launcher: ^6.3.1
  rate_my_app: ^2.3.2
  upgrader: ^12.3.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/onboarding/
    - assets/icons/
    - assets/icons/tools/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
